### ISSUE TITLE
Add more in depth documentation.

### ISSUE THREAD

**Issue by pgr4567** [Danny-Dasilva/Python-HID-USB-API#1]
Hi, I am sorry, that this is not really an appropriate issue, so feel free to close it. 
I was just wondering how you determined the hex string you send for CTRL-ALT-T. I am trying to do something similar with a different key binding and I dont know how to create the hex string for example for ALT+F4.
I would appreciate if you could give me some information about that.
Thank you and kind regards,
pgr4567

**Comment by Danny-Dasilva** [comment]
All the bytes are written in the `send_report` function inside `Py_Keyboard/HID.py` so feel free to change that write function to your use case. 

The byte codes for each character are in `Py_Keyboard/keycodes.py` there you can find the codes you need such as `F4 = 0x3D
    """Function key F4"""` and ` LEFT_ALT = 0xE2
    """Alt modifier left of the spacebar"""` .

Along with this I added returns so you can print out the bytes written in each function. Updated the README as well. 

Your should be able to retool the send `send_report` to write your hex strings out. All the keys are in that `keycodes` .py file if you need specific ones.

 Let me know if this helps, if not I can refactor the write to hid function out so you can have a 1 to 1 mapping of the write and press function out. 
@pgr4567

**Comment by pgr4567** [comment]
Thank you so much for your quick reply!
Your explanation helped me a lot and I successfully implemented your project for my usecase.
Again, thank you and kind regards.
