### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/dev/hidg0'

### ISSUE THREAD

**Issue by nsde** [Danny-Dasilva/Python-HID-USB-API#3]
Hey, I ran into this issue.

```py
  File "(censored)", line 9, in <module>
    keys = Keyboard()
  File "/usr/local/lib/python3.8/dist-packages/Py_Keyboard/HID.py", line 461, in __init__
    self.release_all()
  File "/usr/local/lib/python3.8/dist-packages/Py_Keyboard/HID.py", line 553, in release_all
    send_report(self.report)
  File "/usr/local/lib/python3.8/dist-packages/Py_Keyboard/HID.py", line 627, in send_report
    with open('/dev/hidg0', 'rb+') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/dev/hidg0'
```

My (simplified!) code is 
```py
from Py_Keyboard.HID import Keyboard
keys = Keyboard()
```

**Comment by Danny-Dasilva** [comment]
This just means that you have not configured your Pi as a HID device. You need to complete the setup from this tutorial https://randomnerdtutorials.com/raspberry-pi-zero-usb-keyboard-hid (in the main ReadMe of this repository). If your pi is not configured in this manner this repository won't work as it is not setup in HID mode. I will update the main readme to make this more clear.

**Comment by nsde** [comment]
Oh, so I have to use a raspberry pi :(
That was not helpful, sorry.

**Comment by Danny-Dasilva** [comment]
So this Repo has the tagline `Python Wrapper for emulating a HID USB device for the raspi zero w` in the main ReadMe so I'm a little confused as to why/how you would be using this without one (or a similar microboard). I am sure you could emulate an HID device on other micro boards or even a larger computer. The purpose of this repo is to emulate a keyboard. This means the device you are running this on is (ideally) plugged into another computer.

If you have a different microboard that you are attempting to run this on feel free to let me know and I can explain setup on it. If your use case is different feel free to explain.

Again reiterating this Repo is for emulating keyboard hardware (Hence HID-`USB`). You would use it by plugging the device running the code provided into a desktop or laptop to do keyboard injection (pretending to be a USB device).

**Comment by nsde** [comment]
Alright then.
