### ISSUE TITLE
License

### ISSUE THREAD

**Issue by The-Login** [Danny-Dasilva/Python-HID-USB-API#4]
Hi Danny!
You may not be aware of this, but legally, without a license, no one can use your code.
And I would really love to use your code! ;)
Check out:

http://opensource.stackexchange.com/q/1720/775

**Comment by Danny-Dasilva** [comment]
Sure, the repo is now under [GPL-3](https://choosealicense.com/licenses/gpl-3.0/). Feel free to use it for any commercial or private use.
